Build based on overlays for each python version
thoth-station/s2i-minimal-notebook pull request #37
Opened 2021-02-16 06:03 UTC by harshad16

Build based on overlays for each python version
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

## Related Issues and Dependencies

Related-to: 
https://github.com/thoth-station/s2i-minimal-notebook/issues/36
https://github.com/thoth-station/s2i-minimal-notebook/issues/20

## Description

This will maintain dependencies on the overlays directory.

2021-02-16 06:03 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **harshad16** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @harshad16` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fs2i-minimal-notebook).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["harshad16"]} -->

2021-02-16 07:57 UTC, pacospace approved these changes
lgtm!! 💯 👍🏼 🥇

2021-02-16 07:57 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/s2i-minimal-notebook/pull/37#pullrequestreview-590959032" title="Approved">pacospace</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **harshad16** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @harshad16` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fs2i-minimal-notebook).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/s2i-minimal-notebook/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["harshad16"]} -->

2021-02-16 18:17 UTC, pacospace commented
Fixes: https://github.com/thoth-station/jupyterlab-requirements/issues/53

2021-02-17 10:19 UTC, pacospace commented
Related-To: https://github.com/thoth-station/thoth-application/issues/924

2021-02-18 19:41 UTC, goern requested changes

2021-02-18 19:41 UTC, goern commented on overlays/python38/Dockerfile
> +ENV ENABLE_MICROPIPENV="1" \
why is this not based on v0.24.2 ?

2021-02-18 19:41 UTC, goern commented on .aicoe-ci.yaml
> +      base-image: "quay.io/thoth-station/s2i-thoth-ubi8-py36:v0.20.1"
not v0.24.2 ?

2021-02-21 17:52 UTC, pacospace commented
Related-To: https://github.com/opendatahub-io/odh-manifests/issues/327

2021-02-23 09:23 UTC, goern commented
@harshad16 @pacospace is this good to be merged?!

2021-02-23 13:44 UTC, harshad16 commented
> is this good to be merged?!
not yet, i will update this PR soon.

2021-03-23 05:33 UTC, merged